// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdnFZJZrR-wGAvsEq9Be0nuqF4EVr79ug',
    appId: '1:393834460570:web:5ad1ecc88d37114100b623',
    messagingSenderId: '393834460570',
    projectId: 'brew-crew-free',
    authDomain: 'brew-crew-free.firebaseapp.com',
    storageBucket: 'brew-crew-free.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2IMXOyP06bJWFhIwheyf1KjPrcP2KeuM',
    appId: '1:393834460570:android:657829af3ce39af800b623',
    messagingSenderId: '393834460570',
    projectId: 'brew-crew-free',
    storageBucket: 'brew-crew-free.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoK6m51ruAMWFUA7ITL1dMrpg6XYosMfA',
    appId: '1:393834460570:ios:c271fc43fb1b49fb00b623',
    messagingSenderId: '393834460570',
    projectId: 'brew-crew-free',
    storageBucket: 'brew-crew-free.appspot.com',
    iosClientId: '393834460570-1ja5dsspaivg9qj7s25gpdbk7vvi22f2.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseFlutterBrewCrewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoK6m51ruAMWFUA7ITL1dMrpg6XYosMfA',
    appId: '1:393834460570:ios:4223601f01ee18a300b623',
    messagingSenderId: '393834460570',
    projectId: 'brew-crew-free',
    storageBucket: 'brew-crew-free.appspot.com',
    iosClientId: '393834460570-kgeifc23r6g7sph7dnirpvocbo3s9nsn.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseFlutterBrewCrewApp.RunnerTests',
  );
}
